version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-custom/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/packages/tsconfig/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/packages/talking-translator/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
