name-template: "talking-translator`v$RESOLVED_VERSION`"
tag-template: "talking-translator`v$RESOLVED_VERSION`"

tag-prefix: talking-translator-

include-labels:
  - "talking-translator`o.x.x`"
  - "talking-translator`x.o.x`"
  - "talking-translator`x.x.o`"
  - "talking-translator`x.x.x`"

version-resolver:
  major:
    labels:
      - "talking-translator`o.x.x`"
  minor:
    labels:
      - "talking-translator`x.o.x`"
  patch:
    labels:
      - "talking-translator`x.x.o`"

categories:
  - title: "Major`o.x.x`"
    label: "talking-translator`o.x.x`"
  - title: "Minor`x.o.x`"
    label: "talking-translator`x.o.x`"
  - title: "Patch`x.x.o`"
    label: "talking-translator`x.x.o`"
  - title: "Other`x.x.x`"
    label: "talking-translator`x.x.x`"

template: |
  # What's Changed
  $CHANGES
