name: "Quality check"

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: Install
      shell: bash
      run: pnpm install --no-frozen-lockfile

    - name: Quality check
      shell: bash
      run: pnpm run qualityCheck
